<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="DateApp.Tests\**" />
    <EmbeddedResource Remove="DateApp.Tests\**" />
    <None Remove="DateApp.Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="DateApp.Tests\DateCalculatorServiceTests.cs" />
    <Compile Include="DateApp.Tests\DateCalculatorTests.cs" />
    <Compile Include="DateApp.Tests\DateParserTests.cs" />
    <Compile Include="DateApp.Tests\SimpleDateTests.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="DateApp.Tests\DateApp.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.assert" Version="2.5.3" />
    <PackageReference Include="xunit.extensibility.core" Version="2.5.3" />
  </ItemGroup>

</Project>
